project:
  type: website
  output-dir: docs

website:
  title: "Bibhabasu Mohapatra"
  site-url: "https://bibhabasu-mohapatra.space/"
  search: false
  twitter-card: 
    creator: "@bibhabasuM1610"
    site: "@bibhabasuM1610"
    card-style: summary_large_image
    image: images/OSBF4303.JPG 
  navbar:
    title: bibhabasum
    right:
      - href: index.qmd
        text: Home
      - href: https://bibhabasu-mohapatra.space/blogs/
        text: Blog
      - href: publication.qmd
        text: Publications
      - icon: github
        href: https://github.com/bibhabasumohapatra
      - icon: youtube
        href: https://www.youtube.com/@bibhabasumohapatra
      - icon: twitter
        href: https://twitter.com/bibhabasuM1610

  page-footer: 
    border: false
    background: light

    left: >-
      © 2025 Bibhabasu Mohapatra

    right: >-
      <a class="link-dark me-1">Made with Quarto💙</a>
    center: >-
        <a class="link-dark me-1" href="mailto:bibhabasu.m@gmail.com" title="Email" target="_blank" rel="noopener"> {{< fa envelope >}}</a>
          <a class="link-dark me-1" href="https://github.com/bibhabasumohapatra" title="GitHub" target="_blank" rel="noopener"> {{< fa brands github >}}</a>
          <a class="link-dark me-1" href="https://www.linkedin.com/in/bibhabasu-mohapatra-3b8205193" title="LinkedIn" target="_blank" rel="noopener"> {{< fa brands linkedin >}}</a>
          <a class="link-dark me-1" href="https://twitter.com/bibhabasuM1610" title="Twitter" target="_blank" rel="noopener"> {{< fa brands twitter >}}</a>
          <a class="link-dark me-1" href="https://www.youtube.com/@bibhabasu" title="YouTube" target="_blank" rel="noopener"> {{< fa brands youtube >}}</a>
          <a class="link-dark me-1" href="https://www.instagram.com/bibhabasufilms/" title="Instagram" target="_blank" rel="noopener"> {{< fa brands instagram >}}</a>

format:
  html:
    theme:
      light:
        - zephyr
        - _assets/styles-elm-light.scss
        - _assets/styles-elm-base.scss
        - _assets/colors.scss
      dark:
        - _assets/zephyr-dark.scss
        - _assets/styles-elm-dark.scss
        - _assets/styles-elm-base.scss
        - _assets/colors.scss
    css:
      - _assets/panelset-extras.css
    highlight-style:
      light: _assets/syntax-elm-light.theme
      dark: _assets/syntax-elm-dark.theme
    code-block-bg: false
    include-in-header:
      text: <script src="https://cdn.counter.dev/script.js" data-id="10454114-dc3f-4c23-a4da-87e7f2c7c58d" data-utcoffset="-4"></script>


    ## here in format we will replace with garrick's sccs themes



