project:
  type: website
  output-dir: docs

website:
  title: "Bibhabasu Mohapatra"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: https://bibhabasumohapatra.github.io/youtube
        text: YouTube
      - href: files/cv.pdf
        text: CV
      - href: https://bibhabasumohapatra.github.io/blog
        text: Blogs
      - href: publication.qmd
        text: publication

format:
  html:
    theme:
      light: [litera, styles.scss]
      dark: [darkly, styles-dark.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto

